// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webapi.EntityFramework;

namespace webapi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211221190850_NextMigration")]
    partial class NextMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("webapi.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Henryk",
                            LastName = "Sienkiewicz"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Władysław",
                            LastName = "Reymont"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Czesław",
                            LastName = "Miłosz"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Wisława",
                            LastName = "Szymborska"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Olga",
                            LastName = "Tokarczuk"
                        });
                });

            modelBuilder.Entity("webapi.Models.Email", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Emails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "henryk.sienkiewicz@przyklad.pl",
                            AuthorId = 1
                        },
                        new
                        {
                            Id = 2,
                            Address = "wladyslaw.reymont@przyklad.pl",
                            AuthorId = 2
                        },
                        new
                        {
                            Id = 3,
                            Address = "czeslaw.milosz@przyklad.pl",
                            AuthorId = 3
                        },
                        new
                        {
                            Id = 4,
                            Address = "wislawa.szymborska@przyklad.pl",
                            AuthorId = 4
                        },
                        new
                        {
                            Id = 5,
                            Address = "olga.tokarczuk@przyklad.pl",
                            AuthorId = 5
                        });
                });

            modelBuilder.Entity("webapi.Models.Email", b =>
                {
                    b.HasOne("webapi.Models.Author", "Author")
                        .WithMany("Emails")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("webapi.Models.Author", b =>
                {
                    b.Navigation("Emails");
                });
#pragma warning restore 612, 618
        }
    }
}
