// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webapi5.EntityFramework;

namespace webapi5.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211220123837_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("webapi5.models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "h.sienkiewicz@example.com",
                            FirstName = "Henryk",
                            LastName = "Sienkiewicz"
                        },
                        new
                        {
                            Id = 2,
                            Email = "w.reymont@example.com",
                            FirstName = "Władysław",
                            LastName = "Reymont"
                        },
                        new
                        {
                            Id = 3,
                            Email = "cz.milosz@example.com",
                            FirstName = "Czesław",
                            LastName = "Miłosz"
                        },
                        new
                        {
                            Id = 4,
                            Email = "w.szymborska@example.com",
                            FirstName = "Wisława",
                            LastName = "Szymborska"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
